---
deployment:
  tasks:
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction 2>/dev/null || /usr/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
